# Generated by Django 3.2 on 2021-05-09 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reskill_america_django_app', '0004_auto_20210509_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reskill_america_django_app.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Certificate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reskill_america_django_app.certificate_type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reskill_america_django_app.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reskill_america_django_app.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reskill_america_django_app.school'),
        ),
    ]
